apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: beta
  name: beta-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /beta
spec:
  rules:
  - http:
      paths:
      - path: /node
        pathType: Prefix
        backend:
          service:
            name: node-service
            port:
              number: 3000