apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: beta
  name: beta-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - beta.hands-on.naijab.com
    secretName: letsencrypt-tls
  rules:
  - host: "beta.hands-on.naijab.com"
    http:
      paths:
      - path: /node
        pathType: Prefix
        backend:
          service:
            name: node-service
            port:
              number: 80
