apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: node-service
  labels:
    app: node-service
spec:
  selector:
    matchLabels:
      app: node-service
  replicas: 1
  template:
    metadata:
      labels:
        app: node-service
    spec:
      containers:
        - name: node-service
          image: ghcr.io/naijab/kubeops-part-time/hands-on/node-service:v.0.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ENV
              value: production
            - name: PORT
              value: "3000"
      imagePullSecrets:
        - name: dockerconfigjson-github-com
