apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: node-service
  labels:
    app: node-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: node-service
