apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: production
  name: production-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - prod.hands-on.naijab.com
    secretName: letsencrypt-tls
  rules:
  - host: "prod.hands-on.naijab.com"
    http:
      paths:
      - path: /node
        pathType: Prefix
        backend:
          service:
            name: node-service
            port:
              number: 80
      - path: /go
        pathType: Prefix
        backend:
          service:
            name: go-service
            port:
              number: 80