apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beta
  name: go-service
  labels:
    app: go-service
spec:
  selector:
    matchLabels:
      app: go-service
  replicas: 1
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
        - name: go-service
          image: ghcr.io/naijab/kubeops-part-time/hands-on/go-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: ENV
              value: beta
            - name: PORT
              value: "3001"
      imagePullSecrets:
        - name: dockerconfigjson-github-com
