apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: go-service
  labels:
    app: go-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: go-service
