on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  node-service-jobs:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ${{ github.repository }}/hands-on/node-service
      WORKING_FOLDER: ./hands-on/node-service

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: "#workflows"
        if: always()

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Run unit test before build production
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.WORKING_FOLDER }}
          file: ./${{ env.WORKING_FOLDER }}/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          target: test

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push production image
        uses: docker/build-push-action@v2
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          context: ./${{ env.WORKING_FOLDER }}
          file: ./${{ env.WORKING_FOLDER }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: production

      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: do-sgp1-kubeops-hands-on-sg

      - name: Create namespace
        run: |
          namespacePresent=`kubectl get namespace | grep production | wc -l`
          if [$namespacePresent -eq 0]
          then
            echo `kubectl create namespace production`
          fi

      - name: Send notification to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: '"{"text": "Build node service completed"}"'
        if: always()
