on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  node-service-jobs:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: ./hands-on/node-service

    env:
      IMAGE_NAME: ${{ github.repository }}/hands-on/node-service:latest

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: "#workflows"
        if: always()

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Run unit test before build production
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          target: test

      - name: Build and push production image
        uses: docker/build-push-action@v2
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: production

      - name: Send notification to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
